# frozen_string_literal: true

source "https://rubygems.org"

gem "cucumber", "9.2"
gem "capybara", "3.40"
gem "selenium-webdriver", "4.21"
gem "rspec", "3.13"
gem "faker", "3.4.1"
gem "allure-cucumber", "2.24.5"
